No Transaction Gossiping and Mempool for Light Clients
celestiaorg/optimint pull request #532
Opened 2022-09-20 09:23 UTC by nashqueue

Ref: #526

2022-09-21 10:32 UTC, tzdybal commented
[Rendered version](https://github.com/celestiaorg/optimint/blob/1425fe0aa1fef0d2dc172b53b553e10e8b5b6a74/docs/lazy-adr/adr-008-mempool-optimint-light-client.md).

2022-09-21 10:49 UTC, tzdybal requested changes
I think we should also mention, that light client will actually gossip a transaction, if the transaction originates from this light node.

2022-09-21 10:49 UTC, tzdybal commented on docs/lazy-adr/adr-008-mempool-optimint-light-client.md
> +Light clients cannot do statafull checks, because they don't have access to the state.
```suggestion
Light clients cannot do statefull checks, because they don't have access to the state.
```

2022-09-25 03:19 UTC, adlerjohn reviewed
Please run a spell checker

2022-09-25 03:19 UTC, adlerjohn commented on docs/lazy-adr/adr-008-mempool-optimint-light-client.md
> +There is wish for the light clients to participate in the P2P Layer. One of the ways a full node participates in the network is to gossip valid transactions throuout the network. Each full-node that
```suggestion
There is wish for the light clients to participate in the P2P Layer. One of the ways a full node participates in the network is to gossip valid transactions throuout the network. Each full-node that receives a transaction sends an ABCI message , `CheckTx`, to the application layer to check for validity, and receives an `abci.ResponseCheckTx`.
```

2022-09-25 09:23 UTC, tzdybal reviewed
Looks good modulo spelling and quoting, as pointed out by John.

2022-09-27 10:43 UTC, tzdybal approved these changes
LGTM

2022-09-27 11:40 UTC, merged